app:
    build: .
    command: rails s 
    volumes:
        - .:/app
        - .:/vendor
    ports:
        - "3000:3000"
    links: 
        - postgres
    volumes_from:
        - postgres

postgres:
    image: postgres:9.5
    container_name: pgds
    volumes:
        - /var/lib/psql
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports: 
        - "5432"
