
default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  port: 5432
  pool: 5

development:
  <<: *default
  database: trakMyRun_development

test:
  <<: *default
  database: trakMyRun_test

